from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
import httpx
import secrets
import urllib.parse
from app.db.session import get_db
from app.models.user import User
from app.models.auth_account import AuthAccount
from app.schemas.auth import (
    Token,
    GoogleAuthInit,
    GoogleAuthExchange,
)
from app.core.security import create_access_token
from app.core.config import settings
from app.api.v1.endpoints.auth import format_user_out

router = APIRouter(prefix="/auth/google", tags=["Google OAuth"])

GOOGLE_AUTH_URL = "https://accounts.google.com/o/oauth2/v2/auth"
GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
GOOGLE_USERINFO_URL = "https://www.googleapis.com/oauth2/v3/userinfo"

@router.get("/init", response_model=GoogleAuthInit)
async def init_google_oauth(
    code_challenge: str = Query(..., description="PKCE Code Challenge generated by the client"),
    code_challenge_method: str = Query("S256", description="PKCE method (S256 recommended)")
):
    """
    Initializes Google OAuth 2.0 PKCE flow for desktop/browser.
    Returns the authorization redirect URL with state and code_challenge.
    """
    state = secrets.token_urlsafe(32)
    params = {
        "client_id": settings.GOOGLE_CLIENT_ID or "papyrbound-dev-client-id",
        "redirect_uri": settings.GOOGLE_REDIRECT_URI,
        "response_type": "code",
        "scope": "openid email profile",
        "state": state,
        "code_challenge": code_challenge,
        "code_challenge_method": code_challenge_method,
        "access_type": "offline",
        "prompt": "consent",
    }
    auth_url = f"{GOOGLE_AUTH_URL}?{urllib.parse.urlencode(params)}"
    return GoogleAuthInit(
        redirect_url=auth_url,
        state=state,
        code_challenge=code_challenge
    )

@router.post("/exchange", response_model=Token)
async def exchange_google_code(
    payload: GoogleAuthExchange,
    db: AsyncSession = Depends(get_db)
):
    """
    Exchanges the Google authorization code + PKCE code_verifier for Papyrbound user session.
    """
    google_client_id = settings.GOOGLE_CLIENT_ID
    google_client_secret = settings.GOOGLE_CLIENT_SECRET

    # If in development mode without live Google credentials, handle structured mock exchange
    if not google_client_id or not google_client_secret:
        mock_google_id = f"google_{hash(payload.code) % 1000000}"
        mock_email = f"user_{mock_google_id}@gmail.com"
        mock_name = "Google Reader"
        
        return await _get_or_create_oauth_user(
            db=db,
            provider="google",
            provider_account_id=mock_google_id,
            email=mock_email,
            display_name=mock_name,
            avatar_url="https://lh3.googleusercontent.com/a/default-user"
        )

    # Production Google Token Exchange
    async with httpx.AsyncClient() as client:
        token_resp = await client.post(
            GOOGLE_TOKEN_URL,
            data={
                "client_id": google_client_id,
                "client_secret": google_client_secret,
                "code": payload.code,
                "code_verifier": payload.code_verifier,
                "grant_type": "authorization_code",
                "redirect_uri": settings.GOOGLE_REDIRECT_URI,
            }
        )
        if token_resp.status_code != 200:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Failed to exchange authorization code with Google."
            )
        tokens = token_resp.json()
        access_token = tokens.get("access_token")

        # Fetch Google Profile
        userinfo_resp = await client.get(
            GOOGLE_USERINFO_URL,
            headers={"Authorization": f"Bearer {access_token}"}
        )
        if userinfo_resp.status_code != 200:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Failed to fetch user profile from Google."
            )
        userinfo = userinfo_resp.json()

    return await _get_or_create_oauth_user(
        db=db,
        provider="google",
        provider_account_id=userinfo["sub"],
        email=userinfo["email"],
        display_name=userinfo.get("name", userinfo["email"].split("@")[0]),
        avatar_url=userinfo.get("picture")
    )

async def _get_or_create_oauth_user(
    db: AsyncSession,
    provider: str,
    provider_account_id: str,
    email: str,
    display_name: str,
    avatar_url: str = None
) -> Token:
    # 1. Check if auth_account already linked
    acc_result = await db.execute(
        select(AuthAccount).where(
            AuthAccount.provider == provider,
            AuthAccount.provider_account_id == provider_account_id
        )
    )
    auth_account = acc_result.scalar_one_or_none()

    if auth_account:
        user_result = await db.execute(
            select(User).where(User.id == auth_account.user_id)
        )
        user = user_result.scalar_one()
    else:
        # 2. Check if a user with this email already exists
        user_result = await db.execute(
            select(User).where(User.email == email.lower())
        )
        user = user_result.scalar_one_or_none()

        if not user:
            # Create a brand new user
            base_username = email.split("@")[0].lower()
            unique_username = f"{base_username}_{secrets.token_hex(2)}"
            user = User(
                email=email.lower(),
                username=unique_username,
                display_name=display_name,
                avatar_url=avatar_url,
                is_active=True,
                is_verified=True,
            )
            db.add(user)
            await db.flush()

        # Link Google AuthAccount
        new_auth_account = AuthAccount(
            user_id=user.id,
            provider=provider,
            provider_account_id=provider_account_id,
        )
        db.add(new_auth_account)
        await db.commit()
        await db.refresh(user)

    access_token = create_access_token(subject=user.id)
    return Token(
        access_token=access_token,
        token_type="bearer",
        expires_in=settings.ACCESS_TOKEN_EXPIRE_MINUTES * 60,
        user=format_user_out(user)
    )
